spring:
    datasource:
        driverClassName: org.h2.Driver
        password: password
        url: jdbc:h2:mem:inslight
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
application-description: Given a string _s_, find the longest palindromic substring in _s_. You may assume that the maximum length of _s_ is 1000.
application-version: 1.0
logging:
    file:
        name: code-challenge-logs.txt
        path: /path/to/a/file